hazelcast:
  cp-subsystem:
    cp-member-count: 10
    locks:
      initializationLock:
        lock-acquire-limit: 0
  diagnostics:
    enabled: false

spring:
  application:
    name: hazelcast-poc
  zipkin:
    baseUrl: http://zipkin:9411

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        cloud:
          sleuth: INFO
