apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-poc
  template:
    metadata:
      labels:
        app: hazelcast-poc
    spec:
      containers:
        - name: hazelcast-poc
          image: hazelcast-poc:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: multicast
              protocol: TCP
              containerPort: 5701
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-poc
spec:
  type: NodePort
  selector:
    app: hazelcast-poc
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30100
    - port: 5701
      name: multicast
      targetPort: 5701